// GENERATED FILE. Source: lib/l10n/app_*.arb
package moe.n4tsu.dextop

import java.util.Locale

internal object NativeStrings {
    fun text(key: String): String {
        val locale = Locale.getDefault()
        val regional = if (locale.country.isBlank()) locale.language else "${locale.language}_${locale.country}"
        return ((values[regional] ?: values[locale.language] ?: values.getValue("en"))[key]
            ?: values.getValue("en")[key]
            ?: key).replace("\\n", "\n")
    }

    private val values = mapOf(
        "ja" to mapOf(
            "nativeAddAndApply" to "追加して適用",
            "nativeAddCurrentAppPlacement" to "現在のアプリ配置を追加",
            "nativeAddCustomResolution" to "カスタム解像度を追加",
            "nativeAddResolution" to "解像度を追加",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Dextop表示の明るさを調整します",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Dextopで再生する音量を調整します",
            "nativeAndroidDesktopFreeform" to "Android デスクトップ（Freeform）",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI デスクトップ",
            "nativeAutomaticLayout" to "自動レイアウト",
            "nativeBackButtons" to "背面ボタン",
            "nativeBackButtonsConfirmMessage" to "現在のカバー画面の動作を終了して、背面ボタンを表示します。",
            "nativeBackButtonsConfirmTitle" to "カバー画面を切り替えますか？",
            "nativeBackButtonsDescription" to "カバー画面をL/R・L2/R2の背面ボタンとして使用します",
            "nativeBlackBerryLayout" to "BlackBerryレイアウト",
            "nativeBlackBerryMode" to "BlackBerryモード",
            "nativeBlackBerryModeDescription" to "スマートフォン向けのコンパクトなキーボードだけを表示します",
            "nativeCancel" to "キャンセル",
            "nativeCast" to "キャスト",
            "nativeCastDescription" to "キャスト先を選択",
            "nativeCastUnavailable" to "Google Castを初期化できませんでした",
            "nativeCasting" to "キャスト中",
            "nativeColorosDesktop" to "ColorOS 系デスクトップ",
            "nativeCompletePlacementEdit" to "配置編集を完了",
            "nativeCouldNotStartApp" to "アプリを起動できませんでした",
            "nativeCoverAndroidDescription" to "カバー画面を通常のAndroidとして使用します。メイン側のDextopセッションは継続します。",
            "nativeCoverDextopDescription" to "カバー画面にメイン側とは独立したDextopセッションを作成します。",
            "nativeCoverDisplay" to "カバーディスプレイ",
            "nativeCoverDisplayDescription" to "カバー画面で通常のAndroidを開くか、独立したDextopセッションを作成します",
            "nativeCoverDisplayFailed" to "カバーディスプレイを変更できませんでした",
            "nativeCursor" to "カーソル",
            "nativeDevice" to "端末",
            "nativeDisplayProfileIsOutOfRange" to "表示プロファイルが範囲外です",
            "nativeEdit" to "編集",
            "nativeEditPlacement" to "配置を編集",
            "nativeEditResolution" to "解像度を編集",
            "nativeEnd" to "終了",
            "nativeExpandWorkspace" to "ワークスペースを展開",
            "nativeFailedToSaveFailedToWriteTo" to "保存できませんでした：端末ストレージへの書き込みに失敗しました。",
            "nativeFailedToSaveUnableToRetrieveRunning" to "保存できませんでした：Dextop上で起動中のアプリを取得できません。",
            "nativeGameBoyStyle" to "ゲームボーイスタイル",
            "nativeGameBoyStyleDescription" to "ゲームボーイ風の十字キー、A/B、SELECT/STARTを表示します",
            "nativeGamepadLayout" to "ゲームパッドレイアウト",
            "nativeHeight" to "高さ",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS デスクトップ",
            "nativeHorizontalHolding" to "横持ち",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI デスクトップ",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI デスクトップ",
            "nativeInputIdle" to "待機中",
            "nativeInputMouse" to "マウス",
            "nativeInputTouch" to "タップ",
            "nativeInputTrackpad" to "トラックパッド",
            "nativeKeyboardHeight" to "キーボードの高さ",
            "nativeKeyboardSettings" to "キーボード設定",
            "nativeKeyboardSettingsDescription" to "ラップトップキーボードの外観をカスタマイズします",
            "nativeKeyboardStyle" to "スタイル",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "黒を基調にした省電力キーボード",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "やわらかな雲色のキーボード",
            "nativeKeyboardThemeCrimson" to "クリムゾン",
            "nativeKeyboardThemeCrimsonDescription" to "折りたたみPCをイメージした暖色のクリムゾン",
            "nativeKeyboardThemeCustomDescription" to "カスタムキーボードテーマ",
            "nativeKeyboardThemeStandard" to "標準",
            "nativeKeyboardThemeStandardDescription" to "落ち着いたダークキーボード",
            "nativeLaptopMode" to "ラップトップモード",
            "nativeLaptopModeDescription" to "折りたたみ端末の下半分にキーボードとトラックパッドを表示します",
            "nativeManualHeight" to "高さを手動調整",
            "nativeMirrorSurfaceUnavailable" to "ミラー表示領域を利用できません",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo デスクトップ",
            "nativeNoAppSelected" to "アプリが選択されていません",
            "nativeNoCastDevices" to "利用可能なGoogle Castデバイスがありません",
            "nativeNoSavedWorkspaces" to "保存済みワークスペースはありません",
            "nativeNothingOsDesktop" to "Nothing OS デスクトップ",
            "nativeOk" to "OK",
            "nativeOpenCoverAndroid" to "通常のAndroidを開く",
            "nativeOpenDextopWithYourSavedAppPlacement" to "保存されたアプリ配置でDextopを開きます",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS デスクトップ",
            "nativePauseDextopAndReturnYourAndroidTo" to "Dextopを一時停止し、Androidを通常操作できる状態へ戻します",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nバッテリー: %3\$d%%  |  %4\$s\nCPU温度: %6\$s  |  入力: %5\$s",
            "nativePermissionDeniedToShizuku" to "Shizukuへの権限が拒否されました",
            "nativePermissionRequestInProgress" to "権限リクエストが進行中です",
            "nativePhysicalKeyboard" to "物理キーボードの入力先を切り替え",
            "nativePhysicalKeyboardDemo" to "物理キーボードの入力先をAndroidとDextopの間で切り替えます。対応端末で外部ディスプレイ接続中に表示されます",
            "nativePhysicalMouse" to "物理マウスの入力先を切り替え",
            "nativePhysicalMouseDemo" to "物理マウスの入力先をAndroidとDextopの間で切り替えます。対応端末で外部ディスプレイ接続中に表示されます",
            "nativePixelAndroidDesktop" to "Pixel Android デスクトップ",
            "nativePleaseInstallShizuku" to "Shizukuをインストールしてください",
            "nativePleaseStartDextopFirst" to "先にDextopを開始してください",
            "nativePleaseStartShizuku" to "Shizukuを起動してください",
            "nativeReconnect" to "再接続",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "表示や接続に問題がある場合に再接続します",
            "nativeRemoveThisResolution" to "この解像度を削除",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Shizukuへの接続と権限許可が必要です",
            "nativeResolution" to "解像度",
            "nativeReturn" to "戻る",
            "nativeRotate180" to "180度回転",
            "nativeRotationReleaseUnsupported" to "画面回転の固定解除に対応していません",
            "nativeSaveAndApply" to "保存して適用",
            "nativeSaveTheCurrentAppArrangementAsA" to "現在のアプリ配置をワークスペースとして保存します",
            "nativeScanAgain" to "再スキャン",
            "nativeScanning" to "スキャン中…",
            "nativeScreenBrightness" to "画面の明るさ",
            "nativeSelectedAppCannotLaunch" to "選択したアプリを起動できません",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "触れた位置をDextopへ直接タップとして送ります",
            "nativeShizukuBinderUnavailable" to "Shizukuへの接続を利用できません",
            "nativeShizukuPermissionCheckTimedOut" to "Shizukuの権限確認がタイムアウトしました",
            "nativeShizukuUnavailable" to "Shizukuを利用できません",
            "nativeStartBackButtons" to "背面ボタンを開始",
            "nativeStartCoverDextop" to "カバー側にDextopセッションを作成",
            "nativeStopBackButtons" to "背面ボタンを終了",
            "nativeStopCasting" to "キャストを終了",
            "nativeStopCoverAndroid" to "Androidセッションを終了",
            "nativeStopCoverDextop" to "カバー側のセッションを終了",
            "nativeSwipeLanguage" to "なぞり入力の言語",
            "nativeSwipeLanguageDescription" to "タップ入力は現在のIMEを引き続き使用します",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Dextopの縦向きと横向きを切り替えます",
            "nativeSwitchDextopResolutionAndDpi" to "Dextopの解像度とDPIを切り替えます",
            "nativeSwitchToResolutionSuffix" to "この解像度とDPIへ切り替えます",
            "nativeTap" to "タップ",
            "nativeTapToExit" to "タップして終了",
            "nativeTapToOpen" to "タップして開く",
            "nativeTemporarilyReturnToAndroid" to "一時的にAndroidに戻る",
            "nativeTerminateYourDextopSession" to "Dextopセッションを終了します",
            "nativeTheThreeFingerGestureIsAnEssential" to "3本指ジェスチャーはDextop使用中に必須の操作方法です。\\n各ボタンをタップすると、ここに機能の説明が表示されます",
            "nativeTheme" to "テーマ",
            "nativeUnknownPermissionResult" to "Shizukuから不明な権限結果が返されました",
            "nativeUseTheScreenAsATrackpadTo" to "画面をトラックパッドとして使い、カーソルを操作します",
            "nativeVerticalHolding" to "縦持ち",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "保存済みワークスペースの表示と、現在の配置の保存ができます",
            "nativeVirtualGamepad" to "仮想ゲームパッド",
            "nativeVirtualGamepadDescription" to "ABXY、スティック、トリガーなどを備えた仮想ゲームパッドを表示します",
            "nativeVolume" to "音量",
            "nativeWidth" to "幅",
            "nativeWorkSpace" to "ワークスペース",
            "nativeYouCanRearrangeTheLayoutInThe" to "ボタンを長押しして、操作パネル内の配置を並べ替えられます",
        ),
        "en" to mapOf(
            "nativeAddAndApply" to "Add and apply",
            "nativeAddCurrentAppPlacement" to "Add current app layout",
            "nativeAddCustomResolution" to "Add custom resolution",
            "nativeAddResolution" to "Add resolution",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Adjust Dextop display brightness",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Adjust media volume in Dextop",
            "nativeAndroidDesktopFreeform" to "Android Desktop (Freeform)",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI Desktop",
            "nativeAutomaticLayout" to "Automatic layout",
            "nativeBackButtons" to "Back buttons",
            "nativeBackButtonsConfirmMessage" to "The current cover-display activity will end before the back buttons appear.",
            "nativeBackButtonsConfirmTitle" to "Switch the cover display?",
            "nativeBackButtonsDescription" to "Use the cover display as L/R and L2/R2 shoulder buttons",
            "nativeBlackBerryLayout" to "BlackBerry layout",
            "nativeBlackBerryMode" to "BlackBerry mode",
            "nativeBlackBerryModeDescription" to "Show a compact phone keyboard without a trackpad.",
            "nativeCancel" to "Cancel",
            "nativeCast" to "Cast",
            "nativeCastDescription" to "Choose a cast receiver",
            "nativeCastUnavailable" to "Google Cast could not be initialized",
            "nativeCasting" to "Casting",
            "nativeColorosDesktop" to "ColorOS desktop",
            "nativeCompletePlacementEdit" to "Complete placement edit",
            "nativeCouldNotStartApp" to "Could not start app",
            "nativeCoverAndroidDescription" to "Use the cover display for normal Android while the main Dextop session continues.",
            "nativeCoverDextopDescription" to "Create a Dextop session on the cover display independently from the main session.",
            "nativeCoverDisplay" to "Cover display",
            "nativeCoverDisplayDescription" to "Open Android or create an independent Dextop session on the cover display",
            "nativeCoverDisplayFailed" to "Could not update the cover display",
            "nativeCursor" to "Cursor",
            "nativeDevice" to "Device",
            "nativeDisplayProfileIsOutOfRange" to "Display profile is out of range",
            "nativeEdit" to "Edit",
            "nativeEditPlacement" to "Edit placement",
            "nativeEditResolution" to "Edit resolution",
            "nativeEnd" to "End",
            "nativeExpandWorkspace" to "Expand workspace",
            "nativeFailedToSaveFailedToWriteTo" to "Failed to save: Failed to write to device storage.",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Failed to save: Unable to retrieve running apps on Dextop.",
            "nativeGameBoyStyle" to "Game Boy style",
            "nativeGameBoyStyleDescription" to "Show a Game Boy-inspired D-pad, A/B, and SELECT/START.",
            "nativeGamepadLayout" to "Gamepad layout",
            "nativeHeight" to "Height",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS Desktop",
            "nativeHorizontalHolding" to "Landscape",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI Desktop",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI Desktop",
            "nativeInputIdle" to "Idle",
            "nativeInputMouse" to "Mouse",
            "nativeInputTouch" to "Touch",
            "nativeInputTrackpad" to "Trackpad",
            "nativeKeyboardHeight" to "Keyboard height",
            "nativeKeyboardSettings" to "Keyboard settings",
            "nativeKeyboardSettingsDescription" to "Customize the appearance of the laptop keyboard",
            "nativeKeyboardStyle" to "Style",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "True-black power-saving keyboard",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "Soft cloud blue keyboard",
            "nativeKeyboardThemeCrimson" to "Crimson",
            "nativeKeyboardThemeCrimsonDescription" to "Warm crimson inspired by foldable PCs",
            "nativeKeyboardThemeCustomDescription" to "Custom keyboard theme",
            "nativeKeyboardThemeStandard" to "Standard",
            "nativeKeyboardThemeStandardDescription" to "Neutral dark keyboard",
            "nativeLaptopMode" to "Laptop mode",
            "nativeLaptopModeDescription" to "Show a keyboard and trackpad on the lower half of a foldable device.",
            "nativeManualHeight" to "Manual height",
            "nativeMirrorSurfaceUnavailable" to "The mirror surface is unavailable",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo Desktop",
            "nativeNoAppSelected" to "No app selected",
            "nativeNoCastDevices" to "No Google Cast devices are available",
            "nativeNoSavedWorkspaces" to "No saved workspaces",
            "nativeNothingOsDesktop" to "Nothing OS Desktop",
            "nativeOk" to "OK",
            "nativeOpenCoverAndroid" to "Open Android on cover display",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Open Dextop with your saved app placement",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS Desktop",
            "nativePauseDextopAndReturnYourAndroidTo" to "Pause Dextop and return Android to normal operation.",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nBattery: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  Input: %5\$s",
            "nativePermissionDeniedToShizuku" to "Shizuku permission was denied",
            "nativePermissionRequestInProgress" to "Permission request in progress",
            "nativePhysicalKeyboard" to "Switch physical keyboard destination",
            "nativePhysicalKeyboardDemo" to "Switch the physical keyboard between Android and Dextop. Available on supported devices while an external display is connected.",
            "nativePhysicalMouse" to "Switch physical mouse destination",
            "nativePhysicalMouseDemo" to "Switch the physical mouse between Android and Dextop. Available on supported devices while an external display is connected.",
            "nativePixelAndroidDesktop" to "Pixel Android Desktop",
            "nativePleaseInstallShizuku" to "Please install Shizuku",
            "nativePleaseStartDextopFirst" to "Please start Dextop first",
            "nativePleaseStartShizuku" to "Please start Shizuku",
            "nativeReconnect" to "Reconnect",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Reconnect if you have display or connection problems",
            "nativeRemoveThisResolution" to "Delete this resolution",
            "nativeRequiresConnectionToShizukuAndPermissions" to "A Shizuku connection and permission are required",
            "nativeResolution" to "Resolution",
            "nativeReturn" to "Back",
            "nativeRotate180" to "Rotate 180°",
            "nativeRotationReleaseUnsupported" to "Releasing rotation lock is not supported",
            "nativeSaveAndApply" to "Save and apply",
            "nativeSaveTheCurrentAppArrangementAsA" to "Save the current app arrangement as a workspace",
            "nativeScanAgain" to "Scan again",
            "nativeScanning" to "Scanning…",
            "nativeScreenBrightness" to "Screen brightness",
            "nativeSelectedAppCannotLaunch" to "The selected app cannot be launched",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Sends the touched position directly to Dextop as a tap",
            "nativeShizukuBinderUnavailable" to "The Shizuku connection is unavailable",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku permission check timed out",
            "nativeShizukuUnavailable" to "Shizuku is unavailable",
            "nativeStartBackButtons" to "Start back buttons",
            "nativeStartCoverDextop" to "Create Dextop session on cover display",
            "nativeStopBackButtons" to "End back buttons",
            "nativeStopCasting" to "Stop casting",
            "nativeStopCoverAndroid" to "End Android session",
            "nativeStopCoverDextop" to "End cover Dextop session",
            "nativeSwipeLanguage" to "Swipe typing language",
            "nativeSwipeLanguageDescription" to "Tap typing continues to use your current IME",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Switch Dextop between portrait and landscape",
            "nativeSwitchDextopResolutionAndDpi" to "Change Dextop resolution and DPI",
            "nativeSwitchToResolutionSuffix" to "Switch to this resolution and DPI",
            "nativeTap" to "Tap",
            "nativeTapToExit" to "Tap to exit",
            "nativeTapToOpen" to "Tap to open",
            "nativeTemporarilyReturnToAndroid" to "Temporarily return to Android",
            "nativeTerminateYourDextopSession" to "End the Dextop session",
            "nativeTheThreeFingerGestureIsAnEssential" to "The three-finger gesture is essential while using Dextop.\\nTap a button to see what it does.",
            "nativeTheme" to "Theme",
            "nativeUnknownPermissionResult" to "Shizuku returned an unknown permission result",
            "nativeUseTheScreenAsATrackpadTo" to "Use the screen as a trackpad to control the cursor",
            "nativeVerticalHolding" to "Portrait",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "View saved workspaces and save current arrangement",
            "nativeVirtualGamepad" to "Virtual Gamepad",
            "nativeVirtualGamepadDescription" to "Show a virtual gamepad with ABXY, sticks, triggers, and system buttons.",
            "nativeVolume" to "Volume",
            "nativeWidth" to "Width",
            "nativeWorkSpace" to "Workspace",
            "nativeYouCanRearrangeTheLayoutInThe" to "You can rearrange the layout in the control panel by long-pressing the button.",
        ),
        "zh" to mapOf(
            "nativeAddAndApply" to "添加并应用",
            "nativeAddCurrentAppPlacement" to "添加当前应用布局",
            "nativeAddCustomResolution" to "添加自定义分辨率",
            "nativeAddResolution" to "添加分辨率",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "调整桌面显示的亮度",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "调整 Dextop 上的播放音量",
            "nativeAndroidDesktopFreeform" to "Android 桌面（自由格式）",
            "nativeAsusZenuiRogUiDesktop" to "华硕 ZenUI / ROG UI 桌面",
            "nativeAutomaticLayout" to "自动布局",
            "nativeBackButtons" to "背部按键",
            "nativeBackButtonsConfirmMessage" to "显示背部按键前，将结束当前的外屏操作。",
            "nativeBackButtonsConfirmTitle" to "切换外屏模式？",
            "nativeBackButtonsDescription" to "将外屏用作 L/R 和 L2/R2 肩键",
            "nativeBlackBerryLayout" to "BlackBerry 布局",
            "nativeBlackBerryMode" to "BlackBerry 模式",
            "nativeBlackBerryModeDescription" to "显示不带触控板的紧凑型手机键盘。",
            "nativeCancel" to "取消",
            "nativeCast" to "投射",
            "nativeCastDescription" to "选择投射接收器",
            "nativeCastUnavailable" to "无法初始化 Google Cast",
            "nativeCasting" to "正在投射",
            "nativeColorosDesktop" to "ColorOS桌面",
            "nativeCompletePlacementEdit" to "完成布局编辑",
            "nativeCouldNotStartApp" to "无法启动应用程序",
            "nativeCoverAndroidDescription" to "将外屏用作普通 Android，主屏上的 Dextop 会话会继续运行。",
            "nativeCoverDextopDescription" to "在外屏创建独立于主屏会话的 Dextop 会话。",
            "nativeCoverDisplay" to "外屏",
            "nativeCoverDisplayDescription" to "在外屏打开 Android，或创建独立的 Dextop 会话",
            "nativeCoverDisplayFailed" to "无法更改外屏",
            "nativeCursor" to "光标",
            "nativeDevice" to "设备",
            "nativeDisplayProfileIsOutOfRange" to "显示配置文件超出范围",
            "nativeEdit" to "编辑",
            "nativeEditPlacement" to "编辑布局",
            "nativeEditResolution" to "编辑分辨率",
            "nativeEnd" to "结束",
            "nativeExpandWorkspace" to "展开工作区",
            "nativeFailedToSaveFailedToWriteTo" to "保存失败：无法写入设备存储。",
            "nativeFailedToSaveUnableToRetrieveRunning" to "保存失败：无法检索 Dextop 上正在运行的应用程序。",
            "nativeGameBoyStyle" to "Game Boy 风格",
            "nativeGameBoyStyleDescription" to "显示 Game Boy 风格的方向键、A/B 和 SELECT/START。",
            "nativeGamepadLayout" to "游戏手柄布局",
            "nativeHeight" to "高度",
            "nativeHonorMagicosDesktop" to "荣耀MagicOS桌面",
            "nativeHorizontalHolding" to "横向",
            "nativeHuaweiEmuiDesktop" to "华为EMUI桌面",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI 桌面",
            "nativeInputIdle" to "空闲",
            "nativeInputMouse" to "鼠标",
            "nativeInputTouch" to "触摸",
            "nativeInputTrackpad" to "触控板",
            "nativeKeyboardHeight" to "键盘高度",
            "nativeKeyboardSettings" to "键盘设置",
            "nativeKeyboardSettingsDescription" to "自定义笔记本键盘的外观",
            "nativeKeyboardStyle" to "样式",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "以纯黑为主的省电键盘",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "柔和的云朵蓝键盘",
            "nativeKeyboardThemeCrimson" to "深红",
            "nativeKeyboardThemeCrimsonDescription" to "灵感来自折叠电脑的暖红色",
            "nativeKeyboardThemeCustomDescription" to "自定义键盘主题",
            "nativeKeyboardThemeStandard" to "标准",
            "nativeKeyboardThemeStandardDescription" to "中性的深色键盘",
            "nativeLaptopMode" to "笔记本模式",
            "nativeLaptopModeDescription" to "在折叠设备的下半屏显示键盘和触控板。",
            "nativeManualHeight" to "手动调整高度",
            "nativeMirrorSurfaceUnavailable" to "镜像显示区域不可用",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo 桌面",
            "nativeNoAppSelected" to "未选择应用程序",
            "nativeNoCastDevices" to "没有可用的 Google Cast 设备",
            "nativeNoSavedWorkspaces" to "没有保存的工作区",
            "nativeNothingOsDesktop" to "Nothing OS 桌面",
            "nativeOk" to "确定",
            "nativeOpenCoverAndroid" to "在外屏打开 Android",
            "nativeOpenDextopWithYourSavedAppPlacement" to "使用已保存的应用布局打开 Dextop",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS 桌面",
            "nativePauseDextopAndReturnYourAndroidTo" to "暂停 Dextop，并使 Android 恢复正常操作。",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\n电池: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  输入: %5\$s",
            "nativePermissionDeniedToShizuku" to "Shizuku 权限被拒绝",
            "nativePermissionRequestInProgress" to "权限请求正在进行中",
            "nativePhysicalKeyboard" to "切换物理键盘输入目标",
            "nativePhysicalKeyboardDemo" to "在 Android 和 Dextop 之间切换物理键盘。外接显示器连接到受支持的设备时可用。",
            "nativePhysicalMouse" to "切换物理鼠标输入目标",
            "nativePhysicalMouseDemo" to "在 Android 和 Dextop 之间切换物理鼠标。外接显示器连接到受支持的设备时可用。",
            "nativePixelAndroidDesktop" to "Pixel Android 桌面",
            "nativePleaseInstallShizuku" to "请安装 Shizuku",
            "nativePleaseStartDextopFirst" to "请先启动 Dextop",
            "nativePleaseStartShizuku" to "请启动 Shizuku",
            "nativeReconnect" to "重新连接",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "如果出现显示或连接问题，请重新连接",
            "nativeRemoveThisResolution" to "删除此分辨率",
            "nativeRequiresConnectionToShizukuAndPermissions" to "需要连接到 Shizuku 并获得权限",
            "nativeResolution" to "分辨率",
            "nativeReturn" to "返回",
            "nativeRotate180" to "旋转 180°",
            "nativeRotationReleaseUnsupported" to "不支持解除屏幕旋转锁定",
            "nativeSaveAndApply" to "保存并应用",
            "nativeSaveTheCurrentAppArrangementAsA" to "将当前应用程序排列保存为工作区",
            "nativeScanAgain" to "重新扫描",
            "nativeScanning" to "正在扫描…",
            "nativeScreenBrightness" to "屏幕亮度",
            "nativeSelectedAppCannotLaunch" to "无法启动所选应用",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "将触摸位置作为点击直接发送到 Dextop",
            "nativeShizukuBinderUnavailable" to "Shizuku 连接不可用",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku 权限检查超时",
            "nativeShizukuUnavailable" to "Shizuku 不可用",
            "nativeStartBackButtons" to "启动背部按键",
            "nativeStartCoverDextop" to "在外屏创建 Dextop 会话",
            "nativeStopBackButtons" to "结束背部按键",
            "nativeStopCasting" to "停止投射",
            "nativeStopCoverAndroid" to "结束 Android 会话",
            "nativeStopCoverDextop" to "结束外屏 Dextop 会话",
            "nativeSwipeLanguage" to "滑行输入语言",
            "nativeSwipeLanguageDescription" to "点按输入仍使用当前输入法",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "在 Dextop 的纵向和横向之间切换",
            "nativeSwitchDextopResolutionAndDpi" to "切换 Dextop 分辨率和 DPI",
            "nativeSwitchToResolutionSuffix" to "切换到此分辨率和 DPI",
            "nativeTap" to "点击",
            "nativeTapToExit" to "点击退出",
            "nativeTapToOpen" to "点击打开",
            "nativeTemporarilyReturnToAndroid" to "暂时返回 Android",
            "nativeTerminateYourDextopSession" to "终止您的 Dextop 会话",
            "nativeTheThreeFingerGestureIsAnEssential" to "三指手势是使用Dextop时必不可少的操作方式。 \\n点击每个按钮可在此处查看功能说明",
            "nativeTheme" to "主题",
            "nativeUnknownPermissionResult" to "Shizuku 返回了未知的权限结果",
            "nativeUseTheScreenAsATrackpadTo" to "使用屏幕作为触控板来控制光标",
            "nativeVerticalHolding" to "纵向",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "查看已保存的工作区并保存当前排列",
            "nativeVirtualGamepad" to "虚拟游戏手柄",
            "nativeVirtualGamepadDescription" to "显示带有 ABXY、摇杆、扳机键和系统按键的虚拟游戏手柄。",
            "nativeVolume" to "音量",
            "nativeWidth" to "宽度",
            "nativeWorkSpace" to "工作区",
            "nativeYouCanRearrangeTheLayoutInThe" to "您可以通过长按按钮来重新排列控制面板中的布局。",
        ),
        "ko" to mapOf(
            "nativeAddAndApply" to "추가 및 적용",
            "nativeAddCurrentAppPlacement" to "현재 앱 배치 추가",
            "nativeAddCustomResolution" to "맞춤 해상도 추가",
            "nativeAddResolution" to "해상도 추가",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Dextop 디스플레이의 밝기를 조정합니다.",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Dextop에서 재생할 볼륨을 조정합니다.",
            "nativeAndroidDesktopFreeform" to "Android 데스크톱(Freeform)",
            "nativeAsusZenuiRogUiDesktop" to "ASUS ZenUI / ROG UI 데스크톱",
            "nativeAutomaticLayout" to "자동 레이아웃",
            "nativeBackButtons" to "후면 버튼",
            "nativeBackButtonsConfirmMessage" to "후면 버튼을 표시하기 전에 현재 커버 화면 동작을 종료합니다.",
            "nativeBackButtonsConfirmTitle" to "커버 화면을 전환할까요?",
            "nativeBackButtonsDescription" to "커버 화면을 L/R 및 L2/R2 숄더 버튼으로 사용합니다",
            "nativeBlackBerryLayout" to "BlackBerry 레이아웃",
            "nativeBlackBerryMode" to "BlackBerry 모드",
            "nativeBlackBerryModeDescription" to "트랙패드 없이 휴대전화용 소형 키보드를 표시합니다.",
            "nativeCancel" to "취소",
            "nativeCast" to "전송",
            "nativeCastDescription" to "전송할 기기 선택",
            "nativeCastUnavailable" to "Google Cast를 초기화할 수 없습니다",
            "nativeCasting" to "전송 중",
            "nativeColorosDesktop" to "ColorOS 기반 데스크톱",
            "nativeCompletePlacementEdit" to "배치 편집 완료",
            "nativeCouldNotStartApp" to "앱을 시작할 수 없습니다.",
            "nativeCoverAndroidDescription" to "메인 Dextop 세션을 유지한 채 커버 화면을 일반 Android로 사용합니다.",
            "nativeCoverDextopDescription" to "메인 세션과 독립된 Dextop 세션을 커버 화면에 만듭니다.",
            "nativeCoverDisplay" to "커버 디스플레이",
            "nativeCoverDisplayDescription" to "커버 화면에서 Android를 열거나 독립적인 Dextop 세션을 만듭니다",
            "nativeCoverDisplayFailed" to "커버 디스플레이를 변경할 수 없습니다",
            "nativeCursor" to "커서",
            "nativeDevice" to "기기",
            "nativeDisplayProfileIsOutOfRange" to "표시 프로필이 범위를 벗어났습니다.",
            "nativeEdit" to "편집",
            "nativeEditPlacement" to "배치 편집",
            "nativeEditResolution" to "해상도 편집",
            "nativeEnd" to "종료",
            "nativeExpandWorkspace" to "작업 공간 펼치기",
            "nativeFailedToSaveFailedToWriteTo" to "저장할 수 없습니다. 기기 저장소에 쓰지 못했습니다.",
            "nativeFailedToSaveUnableToRetrieveRunning" to "저장할 수 없습니다. Dextop에서 실행 중인 앱을 가져올 수 없습니다.",
            "nativeGameBoyStyle" to "게임보이 스타일",
            "nativeGameBoyStyleDescription" to "게임보이풍 십자키, A/B 및 SELECT/START를 표시합니다.",
            "nativeGamepadLayout" to "게임패드 레이아웃",
            "nativeHeight" to "높이",
            "nativeHonorMagicosDesktop" to "HONOR MagicOS 데스크톱",
            "nativeHorizontalHolding" to "가로",
            "nativeHuaweiEmuiDesktop" to "Huawei EMUI 데스크톱",
            "nativeHyperosMiuiDesktop" to "HyperOS / MIUI 데스크톱",
            "nativeInputIdle" to "대기 중",
            "nativeInputMouse" to "마우스",
            "nativeInputTouch" to "터치",
            "nativeInputTrackpad" to "트랙패드",
            "nativeKeyboardHeight" to "키보드 높이",
            "nativeKeyboardSettings" to "키보드 설정",
            "nativeKeyboardSettingsDescription" to "노트북 키보드 모양을 사용자 지정합니다",
            "nativeKeyboardStyle" to "스타일",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "순수한 검정 기반의 절전 키보드",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "부드러운 구름빛 블루 키보드",
            "nativeKeyboardThemeCrimson" to "크림슨",
            "nativeKeyboardThemeCrimsonDescription" to "폴더블 PC에서 영감을 받은 따뜻한 크림슨",
            "nativeKeyboardThemeCustomDescription" to "사용자 지정 키보드 테마",
            "nativeKeyboardThemeStandard" to "표준",
            "nativeKeyboardThemeStandardDescription" to "중성적인 다크 키보드",
            "nativeLaptopMode" to "노트북 모드",
            "nativeLaptopModeDescription" to "폴더블 기기 하단에 키보드와 트랙패드를 표시합니다.",
            "nativeManualHeight" to "높이 수동 조절",
            "nativeMirrorSurfaceUnavailable" to "미러 표시 영역을 사용할 수 없습니다",
            "nativeMotorolaLenovoDesktop" to "Motorola / Lenovo 데스크톱",
            "nativeNoAppSelected" to "앱이 선택되지 않음",
            "nativeNoCastDevices" to "사용 가능한 Google Cast 기기가 없습니다",
            "nativeNoSavedWorkspaces" to "저장된 작업공간 없음",
            "nativeNothingOsDesktop" to "Nothing OS 데스크톱",
            "nativeOk" to "확인",
            "nativeOpenCoverAndroid" to "커버 화면에서 Android 열기",
            "nativeOpenDextopWithYourSavedAppPlacement" to "저장된 앱 배치에서 Dextop을 엽니다.",
            "nativeOriginosFuntouchOsDesktop" to "OriginOS / Funtouch OS 데스크톱",
            "nativePauseDextopAndReturnYourAndroidTo" to "Dextop을 일시 중지하고 Android를 정상적으로 조작할 수 있는 상태로 되돌립니다.",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\n배터리: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  입력: %5\$s",
            "nativePermissionDeniedToShizuku" to "Shizuku에 대한 권한이 거부되었습니다.",
            "nativePermissionRequestInProgress" to "권한 요청이 진행 중입니다.",
            "nativePhysicalKeyboard" to "물리 키보드 입력 대상 전환",
            "nativePhysicalKeyboardDemo" to "물리 키보드를 Android와 Dextop 사이에서 전환합니다. 지원 기기에 외부 디스플레이가 연결된 경우 사용할 수 있습니다.",
            "nativePhysicalMouse" to "물리 마우스 입력 대상 전환",
            "nativePhysicalMouseDemo" to "물리 마우스를 Android와 Dextop 사이에서 전환합니다. 지원 기기에 외부 디스플레이가 연결된 경우 사용할 수 있습니다.",
            "nativePixelAndroidDesktop" to "Pixel Android 데스크톱",
            "nativePleaseInstallShizuku" to "Shizuku를 설치하십시오",
            "nativePleaseStartDextopFirst" to "먼저 Dextop을 시작하십시오.",
            "nativePleaseStartShizuku" to "Shizuku를 시작하십시오.",
            "nativeReconnect" to "재연결",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "화면 표시나 연결에 문제가 있으면 다시 연결합니다.",
            "nativeRemoveThisResolution" to "이 해상도 삭제",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Shizuku에 연결하고 권한이 필요합니다.",
            "nativeResolution" to "해상도",
            "nativeReturn" to "뒤로",
            "nativeRotate180" to "180° 회전",
            "nativeRotationReleaseUnsupported" to "화면 회전 잠금 해제를 지원하지 않습니다",
            "nativeSaveAndApply" to "저장하고 적용",
            "nativeSaveTheCurrentAppArrangementAsA" to "현재 앱 배치를 작업공간으로 저장",
            "nativeScanAgain" to "다시 검색",
            "nativeScanning" to "검색 중…",
            "nativeScreenBrightness" to "화면 밝기",
            "nativeSelectedAppCannotLaunch" to "선택한 앱을 실행할 수 없습니다",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "터치한 위치를 Dextop에 직접 탭으로 보냅니다.",
            "nativeShizukuBinderUnavailable" to "Shizuku 연결을 사용할 수 없습니다",
            "nativeShizukuPermissionCheckTimedOut" to "Shizuku의 권한 확인 시간이 초과되었습니다.",
            "nativeShizukuUnavailable" to "Shizuku를 사용할 수 없습니다",
            "nativeStartBackButtons" to "후면 버튼 시작",
            "nativeStartCoverDextop" to "커버 화면에 Dextop 세션 만들기",
            "nativeStopBackButtons" to "후면 버튼 종료",
            "nativeStopCasting" to "전송 중지",
            "nativeStopCoverAndroid" to "Android 세션 종료",
            "nativeStopCoverDextop" to "커버 Dextop 세션 종료",
            "nativeSwipeLanguage" to "스와이프 입력 언어",
            "nativeSwipeLanguageDescription" to "탭 입력은 현재 입력기를 계속 사용합니다",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Dextop의 세로 방향과 가로 방향을 전환합니다.",
            "nativeSwitchDextopResolutionAndDpi" to "Dextop 해상도와 DPI 간 전환",
            "nativeSwitchToResolutionSuffix" to "이 해상도와 DPI로 전환합니다",
            "nativeTap" to "탭",
            "nativeTapToExit" to "탭하여 종료",
            "nativeTapToOpen" to "탭하여 열기",
            "nativeTemporarilyReturnToAndroid" to "일시적으로 Android로 돌아가기",
            "nativeTerminateYourDextopSession" to "Dextop 세션을 종료합니다.",
            "nativeTheThreeFingerGestureIsAnEssential" to "세 손가락 제스처는 Dextop 사용 중에 필수적인 조작 방법입니다. \\n각 버튼을 탭하면 여기에 기능 설명이 표시됩니다.",
            "nativeTheme" to "테마",
            "nativeUnknownPermissionResult" to "Shizuku에서 알 수 없는 권한 결과를 반환했습니다",
            "nativeUseTheScreenAsATrackpadTo" to "화면을 트랙패드로 사용하여 커서를 조작합니다.",
            "nativeVerticalHolding" to "세로",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "저장된 작업 공간을 표시하고 현재 배치를 저장할 수 있습니다.",
            "nativeVirtualGamepad" to "가상 게임패드",
            "nativeVirtualGamepadDescription" to "ABXY, 스틱, 트리거 및 시스템 버튼이 있는 가상 게임패드를 표시합니다.",
            "nativeVolume" to "볼륨",
            "nativeWidth" to "너비",
            "nativeWorkSpace" to "작업 공간",
            "nativeYouCanRearrangeTheLayoutInThe" to "버튼을 길게 눌러 조작 패널의 배치를 정렬할 수 있습니다.",
        ),
        "ru" to mapOf(
            "nativeAddAndApply" to "Добавить и применить",
            "nativeAddCurrentAppPlacement" to "Добавить текущее место размещения приложения",
            "nativeAddCustomResolution" to "Добавить собственное разрешение",
            "nativeAddResolution" to "Добавить разрешение",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Настройка яркости дисплея рабочего стола",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Отрегулируйте громкость воспроизведения на Dextop",
            "nativeAndroidDesktopFreeform" to "Рабочий стол Android (свободная форма)",
            "nativeAsusZenuiRogUiDesktop" to "Рабочий стол ASUS ZenUI/ROG UI",
            "nativeAutomaticLayout" to "Автоматическая раскладка",
            "nativeBackButtons" to "Задние кнопки",
            "nativeBackButtonsConfirmMessage" to "Текущая работа внешнего экрана будет завершена перед показом задних кнопок.",
            "nativeBackButtonsConfirmTitle" to "Переключить внешний экран?",
            "nativeBackButtonsDescription" to "Использовать внешний экран как кнопки L/R и L2/R2",
            "nativeBlackBerryLayout" to "Раскладка BlackBerry",
            "nativeBlackBerryMode" to "Режим BlackBerry",
            "nativeBlackBerryModeDescription" to "Показывает компактную клавиатуру телефона без трекпада.",
            "nativeCancel" to "Отмена",
            "nativeCast" to "Трансляция",
            "nativeCastDescription" to "Выбрать устройство трансляции",
            "nativeCastUnavailable" to "Не удалось инициализировать Google Cast",
            "nativeCasting" to "Трансляция",
            "nativeColorosDesktop" to "Рабочий стол ColorOS",
            "nativeCompletePlacementEdit" to "Завершить редактирование места размещения",
            "nativeCouldNotStartApp" to "Не удалось запустить приложение",
            "nativeCoverAndroidDescription" to "Использует внешний экран для обычного Android, не завершая сеанс Dextop на основном экране.",
            "nativeCoverDextopDescription" to "Создаёт на внешнем экране независимый от основного сеанс Dextop.",
            "nativeCoverDisplay" to "Внешний экран",
            "nativeCoverDisplayDescription" to "Открывает Android или создаёт независимый сеанс Dextop на внешнем экране",
            "nativeCoverDisplayFailed" to "Не удалось изменить внешний экран",
            "nativeCursor" to "Курсор",
            "nativeDevice" to "Устройство",
            "nativeDisplayProfileIsOutOfRange" to "Профиль дисплея находится вне диапазона",
            "nativeEdit" to "Изменить",
            "nativeEditPlacement" to "Изменить место размещения",
            "nativeEditResolution" to "Изменить разрешение",
            "nativeEnd" to "Завершить",
            "nativeExpandWorkspace" to "Расширить рабочую область",
            "nativeFailedToSaveFailedToWriteTo" to "Не удалось сохранить: не удалось записать в память устройства.",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Не удалось сохранить: невозможно получить запущенные приложения на Dextop.",
            "nativeGameBoyStyle" to "Стиль Game Boy",
            "nativeGameBoyStyleDescription" to "Показывает D-pad, A/B и SELECT/START в стиле Game Boy.",
            "nativeGamepadLayout" to "Раскладка геймпада",
            "nativeHeight" to "Высота",
            "nativeHonorMagicosDesktop" to "Рабочий стол HONOR MagicOS",
            "nativeHorizontalHolding" to "Альбомная ориентация",
            "nativeHuaweiEmuiDesktop" to "Рабочий стол Huawei EMUI",
            "nativeHyperosMiuiDesktop" to "Рабочий стол HyperOS / MIUI",
            "nativeInputIdle" to "Ожидание",
            "nativeInputMouse" to "Мышь",
            "nativeInputTouch" to "Касание",
            "nativeInputTrackpad" to "Трекпад",
            "nativeKeyboardHeight" to "Высота клавиатуры",
            "nativeKeyboardSettings" to "Настройки клавиатуры",
            "nativeKeyboardSettingsDescription" to "Настройте внешний вид клавиатуры ноутбука",
            "nativeKeyboardStyle" to "Стиль",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "Энергосберегающая клавиатура на чистом чёрном фоне",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "Мягкая облачно-синяя клавиатура",
            "nativeKeyboardThemeCrimson" to "Малиновая",
            "nativeKeyboardThemeCrimsonDescription" to "Тёплый малиновый цвет в стиле складных ПК",
            "nativeKeyboardThemeCustomDescription" to "Пользовательская тема клавиатуры",
            "nativeKeyboardThemeStandard" to "Стандартная",
            "nativeKeyboardThemeStandardDescription" to "Нейтральная тёмная клавиатура",
            "nativeLaptopMode" to "Режим ноутбука",
            "nativeLaptopModeDescription" to "Показать клавиатуру и тачпад на нижней половине складного устройства.",
            "nativeManualHeight" to "Ручная настройка высоты",
            "nativeMirrorSurfaceUnavailable" to "Область зеркального отображения недоступна",
            "nativeMotorolaLenovoDesktop" to "Рабочий стол Motorola / Lenovo",
            "nativeNoAppSelected" to "Приложение не выбрано",
            "nativeNoCastDevices" to "Нет доступных устройств Google Cast",
            "nativeNoSavedWorkspaces" to "Нет сохраненных рабочих пространств",
            "nativeNothingOsDesktop" to "Рабочий стол Nothing OS",
            "nativeOk" to "ОК",
            "nativeOpenCoverAndroid" to "Открыть Android на внешнем экране",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Откройте Dextop с сохраненным местом размещения приложения.",
            "nativeOriginosFuntouchOsDesktop" to "Рабочий стол OriginOS / Funtouch OS",
            "nativePauseDextopAndReturnYourAndroidTo" to "Приостановить Dextop и вернуть Android в состояние обычного управления.",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\nБатарея: %3\$d%%  |  %4\$s\nCPU: %6\$s  |  Ввод: %5\$s",
            "nativePermissionDeniedToShizuku" to "Разрешение Shizuku отклонено",
            "nativePermissionRequestInProgress" to "Запрос разрешения обрабатывается",
            "nativePhysicalKeyboard" to "Переключить назначение физической клавиатуры",
            "nativePhysicalKeyboardDemo" to "Переключает физическую клавиатуру между Android и Dextop. Доступно на поддерживаемых устройствах при подключённом внешнем дисплее.",
            "nativePhysicalMouse" to "Переключить назначение физической мыши",
            "nativePhysicalMouseDemo" to "Переключает физическую мышь между Android и Dextop. Доступно на поддерживаемых устройствах при подключённом внешнем дисплее.",
            "nativePixelAndroidDesktop" to "Рабочий стол Pixel Android",
            "nativePleaseInstallShizuku" to "Установите Shizuku",
            "nativePleaseStartDextopFirst" to "Пожалуйста, сначала запустите Dextop",
            "nativePleaseStartShizuku" to "Запустите Shizuku",
            "nativeReconnect" to "Переподключиться",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Переподключитесь, если у вас возникли проблемы с отображением или подключением.",
            "nativeRemoveThisResolution" to "Удалить это разрешение",
            "nativeRequiresConnectionToShizukuAndPermissions" to "Требуется подключение к Shizuku и разрешения.",
            "nativeResolution" to "Разрешение",
            "nativeReturn" to "Назад",
            "nativeRotate180" to "Повернуть на 180°",
            "nativeRotationReleaseUnsupported" to "Снятие блокировки поворота не поддерживается",
            "nativeSaveAndApply" to "Сохраните и примените",
            "nativeSaveTheCurrentAppArrangementAsA" to "Сохраните текущее расположение приложения как рабочую область.",
            "nativeScanAgain" to "Сканировать снова",
            "nativeScanning" to "Сканирование…",
            "nativeScreenBrightness" to "Яркость экрана",
            "nativeSelectedAppCannotLaunch" to "Не удалось запустить выбранное приложение",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Отправляет положение касания непосредственно в Dextop как касание",
            "nativeShizukuBinderUnavailable" to "Подключение к Shizuku недоступно",
            "nativeShizukuPermissionCheckTimedOut" to "Истекло время проверки разрешения Shizuku",
            "nativeShizukuUnavailable" to "Shizuku недоступен",
            "nativeStartBackButtons" to "Запустить задние кнопки",
            "nativeStartCoverDextop" to "Создать сеанс Dextop на внешнем экране",
            "nativeStopBackButtons" to "Завершить задние кнопки",
            "nativeStopCasting" to "Остановить трансляцию",
            "nativeStopCoverAndroid" to "Завершить сеанс Android",
            "nativeStopCoverDextop" to "Завершить сеанс Dextop",
            "nativeSwipeLanguage" to "Язык ввода свайпом",
            "nativeSwipeLanguageDescription" to "Обычные нажатия продолжают использовать текущую IME",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Переключение между книжной и альбомной ориентацией Dextop",
            "nativeSwitchDextopResolutionAndDpi" to "Переключение разрешения Dextop и DPI",
            "nativeSwitchToResolutionSuffix" to "Переключиться на это разрешение и DPI",
            "nativeTap" to "Касание",
            "nativeTapToExit" to "Нажмите, чтобы выйти",
            "nativeTapToOpen" to "Нажмите, чтобы открыть",
            "nativeTemporarilyReturnToAndroid" to "Временно вернуться в Android",
            "nativeTerminateYourDextopSession" to "Завершите сеанс Dextop",
            "nativeTheThreeFingerGestureIsAnEssential" to "Жест тремя пальцами необходим при работе с Dextop.\\nНажмите кнопку, чтобы увидеть описание её функции.",
            "nativeTheme" to "Тема",
            "nativeUnknownPermissionResult" to "Shizuku вернул неизвестный результат разрешения",
            "nativeUseTheScreenAsATrackpadTo" to "Используйте экран как трекпад для управления курсором",
            "nativeVerticalHolding" to "Портретная ориентация",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "Просмотр сохраненных рабочих пространств и сохранение текущего расположения",
            "nativeVirtualGamepad" to "Виртуальный геймпад",
            "nativeVirtualGamepadDescription" to "Показывает виртуальный геймпад с ABXY, стиками, триггерами и системными кнопками.",
            "nativeVolume" to "Громкость",
            "nativeWidth" to "Ширина",
            "nativeWorkSpace" to "Рабочая область",
            "nativeYouCanRearrangeTheLayoutInThe" to "Вы можете изменить расположение макета на панели управления, удерживая кнопку.",
        ),
        "pt" to mapOf(
            "nativeAddAndApply" to "Adicionar e aplicar",
            "nativeAddCurrentAppPlacement" to "Adicionar disposição atual dos aplicativos",
            "nativeAddCustomResolution" to "Adicionar resolução personalizada",
            "nativeAddResolution" to "Adicionar resolução",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Ajustar o brilho da tela do Dextop",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Ajustar o volume de mídia no Dextop",
            "nativeAndroidDesktopFreeform" to "Desktop Android (forma livre)",
            "nativeAsusZenuiRogUiDesktop" to "Desktop ASUS ZenUI / ROG UI",
            "nativeAutomaticLayout" to "Layout automático",
            "nativeBackButtons" to "Botões traseiros",
            "nativeBackButtonsConfirmMessage" to "A atividade atual da tela externa será encerrada antes de os botões traseiros aparecerem.",
            "nativeBackButtonsConfirmTitle" to "Trocar a tela externa?",
            "nativeBackButtonsDescription" to "Usa a tela externa como botões de ombro L/R e L2/R2",
            "nativeBlackBerryLayout" to "Layout BlackBerry",
            "nativeBlackBerryMode" to "Modo BlackBerry",
            "nativeBlackBerryModeDescription" to "Mostra um teclado compacto para celular sem trackpad.",
            "nativeCancel" to "Cancelar",
            "nativeCast" to "Transmitir",
            "nativeCastDescription" to "Escolher um receptor de transmissão",
            "nativeCastUnavailable" to "Não foi possível inicializar o Google Cast",
            "nativeCasting" to "Transmitindo",
            "nativeColorosDesktop" to "Desktop ColorOS",
            "nativeCompletePlacementEdit" to "Concluir edição da disposição",
            "nativeCouldNotStartApp" to "Não foi possível iniciar o aplicativo",
            "nativeCoverAndroidDescription" to "Use a tela externa com o Android normal enquanto a sessão principal do Dextop continua.",
            "nativeCoverDextopDescription" to "Crie uma sessão Dextop na tela externa, independente da sessão principal.",
            "nativeCoverDisplay" to "Tela externa",
            "nativeCoverDisplayDescription" to "Abra o Android ou crie uma sessão Dextop independente na tela externa",
            "nativeCoverDisplayFailed" to "Não foi possível atualizar a tela externa",
            "nativeCursor" to "Cursor",
            "nativeDevice" to "Dispositivo",
            "nativeDisplayProfileIsOutOfRange" to "O perfil da tela está fora do intervalo",
            "nativeEdit" to "Editar",
            "nativeEditPlacement" to "Editar disposição",
            "nativeEditResolution" to "Editar resolução",
            "nativeEnd" to "Encerrar",
            "nativeExpandWorkspace" to "Expandir espaço de trabalho",
            "nativeFailedToSaveFailedToWriteTo" to "Falha ao salvar: não foi possível gravar no armazenamento do dispositivo.",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Falha ao salvar: não foi possível obter os aplicativos em execução no Dextop.",
            "nativeGameBoyStyle" to "Estilo Game Boy",
            "nativeGameBoyStyleDescription" to "Mostra um direcional, A/B e SELECT/START inspirados no Game Boy.",
            "nativeGamepadLayout" to "Layout do gamepad",
            "nativeHeight" to "Altura",
            "nativeHonorMagicosDesktop" to "Desktop HONOR MagicOS",
            "nativeHorizontalHolding" to "Paisagem",
            "nativeHuaweiEmuiDesktop" to "Desktop Huawei EMUI",
            "nativeHyperosMiuiDesktop" to "Desktop HyperOS / MIUI",
            "nativeInputIdle" to "Inativo",
            "nativeInputMouse" to "Mouse",
            "nativeInputTouch" to "Toque",
            "nativeInputTrackpad" to "Trackpad",
            "nativeKeyboardHeight" to "Altura do teclado",
            "nativeKeyboardSettings" to "Configurações do teclado",
            "nativeKeyboardSettingsDescription" to "Personalize a aparência do teclado do modo laptop",
            "nativeKeyboardStyle" to "Estilo",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "Teclado preto verdadeiro com economia de energia",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "Teclado azul-claro suave",
            "nativeKeyboardThemeCrimson" to "Carmesim",
            "nativeKeyboardThemeCrimsonDescription" to "Carmesim quente inspirado em computadores dobráveis",
            "nativeKeyboardThemeCustomDescription" to "Tema de teclado personalizado",
            "nativeKeyboardThemeStandard" to "Padrão",
            "nativeKeyboardThemeStandardDescription" to "Teclado escuro neutro",
            "nativeLaptopMode" to "Modo laptop",
            "nativeLaptopModeDescription" to "Mostra um teclado e um trackpad na metade inferior de um dispositivo dobrável.",
            "nativeManualHeight" to "Ajuste manual da altura",
            "nativeMirrorSurfaceUnavailable" to "A superfície de espelhamento não está disponível",
            "nativeMotorolaLenovoDesktop" to "Desktop Motorola / Lenovo",
            "nativeNoAppSelected" to "Nenhum aplicativo selecionado",
            "nativeNoCastDevices" to "Nenhum dispositivo Google Cast está disponível",
            "nativeNoSavedWorkspaces" to "Nenhum espaço de trabalho salvo",
            "nativeNothingOsDesktop" to "Desktop Nothing OS",
            "nativeOk" to "OK",
            "nativeOpenCoverAndroid" to "Abrir o Android na tela externa",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Abrir o Dextop com a disposição de aplicativos salva",
            "nativeOriginosFuntouchOsDesktop" to "Desktop OriginOS / Funtouch OS",
            "nativePauseDextopAndReturnYourAndroidTo" to "Pausar o Dextop e retornar o Android ao uso normal.",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\\nBateria: %3\$d%%  |  %4\$s\\nCPU: %6\$s  |  Entrada: %5\$s",
            "nativePermissionDeniedToShizuku" to "A permissão do Shizuku foi negada",
            "nativePermissionRequestInProgress" to "Solicitação de permissão em andamento",
            "nativePhysicalKeyboard" to "Alternar destino do teclado físico",
            "nativePhysicalKeyboardDemo" to "Alterne o teclado físico entre o Android e o Dextop. Disponível em dispositivos compatíveis enquanto uma tela externa estiver conectada.",
            "nativePhysicalMouse" to "Alternar destino do mouse físico",
            "nativePhysicalMouseDemo" to "Alterne o mouse físico entre o Android e o Dextop. Disponível em dispositivos compatíveis enquanto uma tela externa estiver conectada.",
            "nativePixelAndroidDesktop" to "Desktop Android do Pixel",
            "nativePleaseInstallShizuku" to "Instale o Shizuku",
            "nativePleaseStartDextopFirst" to "Inicie o Dextop primeiro",
            "nativePleaseStartShizuku" to "Inicie o Shizuku",
            "nativeReconnect" to "Reconectar",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Reconecte se houver problemas de exibição ou conexão",
            "nativeRemoveThisResolution" to "Excluir esta resolução",
            "nativeRequiresConnectionToShizukuAndPermissions" to "É necessária uma conexão com o Shizuku e a respectiva permissão",
            "nativeResolution" to "Resolução",
            "nativeReturn" to "Voltar",
            "nativeRotate180" to "Girar 180°",
            "nativeRotationReleaseUnsupported" to "Não há suporte para liberar o bloqueio de rotação",
            "nativeSaveAndApply" to "Salvar e aplicar",
            "nativeSaveTheCurrentAppArrangementAsA" to "Salvar a disposição atual dos aplicativos como espaço de trabalho",
            "nativeScanAgain" to "Procurar novamente",
            "nativeScanning" to "Procurando…",
            "nativeScreenBrightness" to "Brilho da tela",
            "nativeSelectedAppCannotLaunch" to "O aplicativo selecionado não pode ser iniciado",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Envia a posição tocada diretamente ao Dextop como um toque",
            "nativeShizukuBinderUnavailable" to "A conexão com o Shizuku não está disponível",
            "nativeShizukuPermissionCheckTimedOut" to "A verificação de permissão do Shizuku expirou",
            "nativeShizukuUnavailable" to "O Shizuku não está disponível",
            "nativeStartBackButtons" to "Iniciar botões traseiros",
            "nativeStartCoverDextop" to "Criar sessão Dextop na tela externa",
            "nativeStopBackButtons" to "Encerrar botões traseiros",
            "nativeStopCasting" to "Parar transmissão",
            "nativeStopCoverAndroid" to "Encerrar sessão do Android",
            "nativeStopCoverDextop" to "Encerrar sessão Dextop da tela externa",
            "nativeSwipeLanguage" to "Idioma da digitação por deslize",
            "nativeSwipeLanguageDescription" to "A digitação por toque continua usando seu IME atual",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Alternar o Dextop entre retrato e paisagem",
            "nativeSwitchDextopResolutionAndDpi" to "Alterar a resolução e o DPI do Dextop",
            "nativeSwitchToResolutionSuffix" to "Alternar para esta resolução e DPI",
            "nativeTap" to "Toque",
            "nativeTapToExit" to "Toque para sair",
            "nativeTapToOpen" to "Toque para abrir",
            "nativeTemporarilyReturnToAndroid" to "Retornar temporariamente ao Android",
            "nativeTerminateYourDextopSession" to "Encerrar a sessão do Dextop",
            "nativeTheThreeFingerGestureIsAnEssential" to "O gesto de três dedos é essencial durante o uso do Dextop.\\nToque em um botão para ver sua função.",
            "nativeTheme" to "Tema",
            "nativeUnknownPermissionResult" to "O Shizuku retornou um resultado de permissão desconhecido",
            "nativeUseTheScreenAsATrackpadTo" to "Use a tela como trackpad para controlar o cursor",
            "nativeVerticalHolding" to "Retrato",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "Veja os espaços de trabalho salvos e salve a disposição atual",
            "nativeVirtualGamepad" to "Gamepad virtual",
            "nativeVirtualGamepadDescription" to "Mostra um gamepad virtual com ABXY, analógicos, gatilhos e botões do sistema.",
            "nativeVolume" to "Volume",
            "nativeWidth" to "Largura",
            "nativeWorkSpace" to "Espaço de trabalho",
            "nativeYouCanRearrangeTheLayoutInThe" to "Mantenha um botão pressionado para reorganizar o painel de controle.",
        ),
        "pt_BR" to mapOf(
            "nativeAddAndApply" to "Adicionar e aplicar",
            "nativeAddCurrentAppPlacement" to "Adicionar disposição atual dos aplicativos",
            "nativeAddCustomResolution" to "Adicionar resolução personalizada",
            "nativeAddResolution" to "Adicionar resolução",
            "nativeAdjustTheBrightnessOfTheDesktopDisplay" to "Ajustar o brilho da tela do Dextop",
            "nativeAdjustTheVolumeOfPlaybackOnDextop" to "Ajustar o volume de mídia no Dextop",
            "nativeAndroidDesktopFreeform" to "Desktop Android (forma livre)",
            "nativeAsusZenuiRogUiDesktop" to "Desktop ASUS ZenUI / ROG UI",
            "nativeAutomaticLayout" to "Layout automático",
            "nativeBackButtons" to "Botões traseiros",
            "nativeBackButtonsConfirmMessage" to "A atividade atual da tela externa será encerrada antes de os botões traseiros aparecerem.",
            "nativeBackButtonsConfirmTitle" to "Trocar a tela externa?",
            "nativeBackButtonsDescription" to "Usa a tela externa como botões de ombro L/R e L2/R2",
            "nativeBlackBerryLayout" to "Layout BlackBerry",
            "nativeBlackBerryMode" to "Modo BlackBerry",
            "nativeBlackBerryModeDescription" to "Mostra um teclado compacto para celular sem trackpad.",
            "nativeCancel" to "Cancelar",
            "nativeCast" to "Transmitir",
            "nativeCastDescription" to "Escolher um receptor de transmissão",
            "nativeCastUnavailable" to "Não foi possível inicializar o Google Cast",
            "nativeCasting" to "Transmitindo",
            "nativeColorosDesktop" to "Desktop ColorOS",
            "nativeCompletePlacementEdit" to "Concluir edição da disposição",
            "nativeCouldNotStartApp" to "Não foi possível iniciar o aplicativo",
            "nativeCoverAndroidDescription" to "Use a tela externa com o Android normal enquanto a sessão principal do Dextop continua.",
            "nativeCoverDextopDescription" to "Crie uma sessão Dextop na tela externa, independente da sessão principal.",
            "nativeCoverDisplay" to "Tela externa",
            "nativeCoverDisplayDescription" to "Abra o Android ou crie uma sessão Dextop independente na tela externa",
            "nativeCoverDisplayFailed" to "Não foi possível atualizar a tela externa",
            "nativeCursor" to "Cursor",
            "nativeDevice" to "Dispositivo",
            "nativeDisplayProfileIsOutOfRange" to "O perfil da tela está fora do intervalo",
            "nativeEdit" to "Editar",
            "nativeEditPlacement" to "Editar disposição",
            "nativeEditResolution" to "Editar resolução",
            "nativeEnd" to "Encerrar",
            "nativeExpandWorkspace" to "Expandir espaço de trabalho",
            "nativeFailedToSaveFailedToWriteTo" to "Falha ao salvar: não foi possível gravar no armazenamento do dispositivo.",
            "nativeFailedToSaveUnableToRetrieveRunning" to "Falha ao salvar: não foi possível obter os aplicativos em execução no Dextop.",
            "nativeGameBoyStyle" to "Estilo Game Boy",
            "nativeGameBoyStyleDescription" to "Mostra um direcional, A/B e SELECT/START inspirados no Game Boy.",
            "nativeGamepadLayout" to "Layout do gamepad",
            "nativeHeight" to "Altura",
            "nativeHonorMagicosDesktop" to "Desktop HONOR MagicOS",
            "nativeHorizontalHolding" to "Paisagem",
            "nativeHuaweiEmuiDesktop" to "Desktop Huawei EMUI",
            "nativeHyperosMiuiDesktop" to "Desktop HyperOS / MIUI",
            "nativeInputIdle" to "Inativo",
            "nativeInputMouse" to "Mouse",
            "nativeInputTouch" to "Toque",
            "nativeInputTrackpad" to "Trackpad",
            "nativeKeyboardHeight" to "Altura do teclado",
            "nativeKeyboardSettings" to "Configurações do teclado",
            "nativeKeyboardSettingsDescription" to "Personalize a aparência do teclado do modo laptop",
            "nativeKeyboardStyle" to "Estilo",
            "nativeKeyboardThemeAmoled" to "AMOLED",
            "nativeKeyboardThemeAmoledDescription" to "Teclado preto verdadeiro com economia de energia",
            "nativeKeyboardThemeCloud" to "Cloud Pop",
            "nativeKeyboardThemeCloudDescription" to "Teclado azul-claro suave",
            "nativeKeyboardThemeCrimson" to "Carmesim",
            "nativeKeyboardThemeCrimsonDescription" to "Carmesim quente inspirado em computadores dobráveis",
            "nativeKeyboardThemeCustomDescription" to "Tema de teclado personalizado",
            "nativeKeyboardThemeStandard" to "Padrão",
            "nativeKeyboardThemeStandardDescription" to "Teclado escuro neutro",
            "nativeLaptopMode" to "Modo laptop",
            "nativeLaptopModeDescription" to "Mostra um teclado e um trackpad na metade inferior de um dispositivo dobrável.",
            "nativeManualHeight" to "Ajuste manual da altura",
            "nativeMirrorSurfaceUnavailable" to "A superfície de espelhamento não está disponível",
            "nativeMotorolaLenovoDesktop" to "Desktop Motorola / Lenovo",
            "nativeNoAppSelected" to "Nenhum aplicativo selecionado",
            "nativeNoCastDevices" to "Nenhum dispositivo Google Cast está disponível",
            "nativeNoSavedWorkspaces" to "Nenhum espaço de trabalho salvo",
            "nativeNothingOsDesktop" to "Desktop Nothing OS",
            "nativeOk" to "OK",
            "nativeOpenCoverAndroid" to "Abrir o Android na tela externa",
            "nativeOpenDextopWithYourSavedAppPlacement" to "Abrir o Dextop com a disposição de aplicativos salva",
            "nativeOriginosFuntouchOsDesktop" to "Desktop OriginOS / Funtouch OS",
            "nativePauseDextopAndReturnYourAndroidTo" to "Pausar o Dextop e retornar o Android ao uso normal.",
            "nativePerformanceHudFormat" to "%1\$.1f FPS  |  %2\$d MB\\nBateria: %3\$d%%  |  %4\$s\\nCPU: %6\$s  |  Entrada: %5\$s",
            "nativePermissionDeniedToShizuku" to "A permissão do Shizuku foi negada",
            "nativePermissionRequestInProgress" to "Solicitação de permissão em andamento",
            "nativePhysicalKeyboard" to "Alternar destino do teclado físico",
            "nativePhysicalKeyboardDemo" to "Alterne o teclado físico entre o Android e o Dextop. Disponível em dispositivos compatíveis enquanto uma tela externa estiver conectada.",
            "nativePhysicalMouse" to "Alternar destino do mouse físico",
            "nativePhysicalMouseDemo" to "Alterne o mouse físico entre o Android e o Dextop. Disponível em dispositivos compatíveis enquanto uma tela externa estiver conectada.",
            "nativePixelAndroidDesktop" to "Desktop Android do Pixel",
            "nativePleaseInstallShizuku" to "Instale o Shizuku",
            "nativePleaseStartDextopFirst" to "Inicie o Dextop primeiro",
            "nativePleaseStartShizuku" to "Inicie o Shizuku",
            "nativeReconnect" to "Reconectar",
            "nativeReconnectIfYouHaveDisplayOrConnection" to "Reconecte se houver problemas de exibição ou conexão",
            "nativeRemoveThisResolution" to "Excluir esta resolução",
            "nativeRequiresConnectionToShizukuAndPermissions" to "É necessária uma conexão com o Shizuku e a respectiva permissão",
            "nativeResolution" to "Resolução",
            "nativeReturn" to "Voltar",
            "nativeRotate180" to "Girar 180°",
            "nativeRotationReleaseUnsupported" to "Não há suporte para liberar o bloqueio de rotação",
            "nativeSaveAndApply" to "Salvar e aplicar",
            "nativeSaveTheCurrentAppArrangementAsA" to "Salvar a disposição atual dos aplicativos como espaço de trabalho",
            "nativeScanAgain" to "Procurar novamente",
            "nativeScanning" to "Procurando…",
            "nativeScreenBrightness" to "Brilho da tela",
            "nativeSelectedAppCannotLaunch" to "O aplicativo selecionado não pode ser iniciado",
            "nativeSendsTheTouchedPositionDirectlyToDextop" to "Envia a posição tocada diretamente ao Dextop como um toque",
            "nativeShizukuBinderUnavailable" to "A conexão com o Shizuku não está disponível",
            "nativeShizukuPermissionCheckTimedOut" to "A verificação de permissão do Shizuku expirou",
            "nativeShizukuUnavailable" to "O Shizuku não está disponível",
            "nativeStartBackButtons" to "Iniciar botões traseiros",
            "nativeStartCoverDextop" to "Criar sessão Dextop na tela externa",
            "nativeStopBackButtons" to "Encerrar botões traseiros",
            "nativeStopCasting" to "Parar transmissão",
            "nativeStopCoverAndroid" to "Encerrar sessão do Android",
            "nativeStopCoverDextop" to "Encerrar sessão Dextop da tela externa",
            "nativeSwipeLanguage" to "Idioma da digitação por deslize",
            "nativeSwipeLanguageDescription" to "A digitação por toque continua usando seu IME atual",
            "nativeSwitchBetweenPortraitAndLandscapeOrientationOf" to "Alternar o Dextop entre retrato e paisagem",
            "nativeSwitchDextopResolutionAndDpi" to "Alterar a resolução e o DPI do Dextop",
            "nativeSwitchToResolutionSuffix" to "Alternar para esta resolução e DPI",
            "nativeTap" to "Toque",
            "nativeTapToExit" to "Toque para sair",
            "nativeTapToOpen" to "Toque para abrir",
            "nativeTemporarilyReturnToAndroid" to "Retornar temporariamente ao Android",
            "nativeTerminateYourDextopSession" to "Encerrar a sessão do Dextop",
            "nativeTheThreeFingerGestureIsAnEssential" to "O gesto de três dedos é essencial durante o uso do Dextop.\\nToque em um botão para ver sua função.",
            "nativeTheme" to "Tema",
            "nativeUnknownPermissionResult" to "O Shizuku retornou um resultado de permissão desconhecido",
            "nativeUseTheScreenAsATrackpadTo" to "Use a tela como trackpad para controlar o cursor",
            "nativeVerticalHolding" to "Retrato",
            "nativeViewSavedWorkspacesAndSaveCurrentArrangement" to "Veja os espaços de trabalho salvos e salve a disposição atual",
            "nativeVirtualGamepad" to "Gamepad virtual",
            "nativeVirtualGamepadDescription" to "Mostra um gamepad virtual com ABXY, analógicos, gatilhos e botões do sistema.",
            "nativeVolume" to "Volume",
            "nativeWidth" to "Largura",
            "nativeWorkSpace" to "Espaço de trabalho",
            "nativeYouCanRearrangeTheLayoutInThe" to "Mantenha um botão pressionado para reorganizar o painel de controle.",
        ),
    )
}
